packages:
  - "."

overrides:
  use-sync-external-store: 1.6.0

allowBuilds:
  "@deepseek-ai/dsh-subprocess-local": true
  "@google/genai": true
  better-sqlite3: false
  esbuild: true
  koffi: true
  node-pty: true
  protobufjs: true

ignoredBuiltDependencies:
  - better-sqlite3

onlyBuiltDependencies:
  - "@deepseek-ai/dsh-subprocess-local"
  - "@google/genai"
  - "esbuild"
  - "koffi"
  - "node-pty"
  - "protobufjs"

minimumReleaseAgeExclude:
  - "@onkernel/sdk@0.97.0"
