export { classify } from "./classify.js";
export { CompileError, compile } from "./compile.js";
export {
  click,
  css,
  extractList,
  extractText,
  fill,
  form,
  hrefField,
  inputRef,
  label,
  landmark,
  literalValue,
  navigate,
  automation,
  role,
  select,
  testId,
  text,
  textField,
  urlField,
} from "./dsl.js";
export { RunLog } from "./events.js";
export { applyPatches, locatorPatch } from "./patches.js";
export {
  acceptRepairedVersion,
  emptyRunStats,
  markVerified,
  promoteVerificationOnSuccess,
  recordFailedRun,
  recordSuccessfulRun,
} from "./verification.js";
export { bindLocatorScope, locatorScope, scopeLabel, scopesEqual } from "./scope.js";
export {
  isAcceptableValidatedRepair,
  isCompleteValidatedRepair,
  parseTerminalRepairResult,
  patchCompatibleWithStep,
  type NoRepairResult,
  type TerminalRepairResult,
  type ValidatedRepairResult,
  type ValidationOutcome,
} from "./repair-result.js";
export {
  DEFAULT_REPAIR_CONSTRAINTS,
  findAction,
  findStep,
  hasLocator,
  isStepValue,
  lookupInput,
  resolveStepValue,
  stepValuePresent,
  type Condition,
  type ExecutionContextId,
  type StepConditions,
  type Action,
  type Automation,
  type AutomationFailure,
  type AutomationPatch,
  type AutomationVerification,
  type AutomationVerificationStatus,
  type AutomationVersionRecord,
  type AutomationVersionStats,
  type ClickStep,
  type ExtractListStep,
  type ExtractTextStep,
  type FailureCategory,
  type FailureClassification,
  type FailureEvidence,
  type FailureType,
  type FillStep,
  type FillValue,
  type ListField,
  type LocatorContext,
  type LocatorDefinition,
  type LocatorScope,
  type NavigateStep,
  type RepairCandidate,
  type RepairConstraints,
  type RepairRequest,
  type RunEvent,
  type RunEventType,
  type SelectStep,
  type Step,
  type StepSafety,
  type StepValue,
} from "./types.js";
